Add implementation of Exit command
BHoM/Robot_Toolkit pull request #466
Opened 2021-08-19 12:25 UTC by IsakNaslundBh

### NOTE: Depends on 

https://github.com/BHoM/BHoM_Adapter/pull/303

 ### Issues addressed by this PR

 Closes #465 

 

Adding support for the Exit command

 ### Test files

 ### Changelog

 ### Additional comments

2021-08-19 13:06 UTC, peterjamesnugent requested changes
Minor check otherwise works well, even without a project loaded.

2021-08-19 13:06 UTC, peterjamesnugent commented on Robot_Adapter/AdapterActions/Execute.cs
> +                m_RobotApplication.Project.Save();
Should we add a check here whether the file has a name?

You can open an empty file and this will return an error.

You could argue that the user opted for `true` on the input but it is also the default value..

2021-08-19 13:09 UTC, peterjamesnugent commented
Forgot to add - I had up to update the .NET Framework to 4.7.2 to get it to build.

2021-08-19 13:20 UTC, IsakNaslundBh commented on Robot_Adapter/AdapterActions/Execute.cs
> +                m_RobotApplication.Project.Save();
yeah, fair enough.

So, if untitled project open, and save is true, then return an error and stop attempts of trying to exit?

2021-08-19 13:36 UTC, peterjamesnugent commented on Robot_Adapter/AdapterActions/Execute.cs
> +                m_RobotApplication.Project.Save();
Yeah I think return error and `false`.

The alternative would be no save and proceed to quit which could result in lost work.

2021-08-19 15:26 UTC, peterjamesnugent approved these changes
LGTM.

We will need to add a similar check for the `Close` command before it is saved - but that can be raised in a separate issue/PR.

2021-08-19 15:27 UTC, peterjamesnugent commented
@BHoMBot check compliance

2021-08-24 19:40 UTC, JosefTaylor commented
noticed we get an error if `SaveBeforeClosing` is true but the file is not yet saved (due to being un-titled); in ETABS/SAP this is handled with a dialogue box from the software, so it's easy for a user to fix, but in Robot it's handled as a BHoM error. Not sure how this will affect testing (make sure bhombot sets the boolean to false, I suppose)

Otherwise, looks great.

2021-08-24 19:55 UTC, peterjamesnugent commented
@JosefTaylor I handle this on Lusas by checking the database name, if it's empty then it returns an error message and `false`.

2021-08-25 07:18 UTC, IsakNaslundBh commented
> Not sure how this will affect testing (make sure bhombot sets the boolean to false, I suppose)

The testing will call the command with false, see https://github.com/BHoM/Test_Toolkit/blob/5a9a870b19da08f202e95261c984a8b60eb53a0d/InteroperabilityTest_Engine/Compute/PushPullCompare.cs#L100

Agree there is some discrepancy between the two, which we may or may not want to remove, but the most important points to me for this command is.

1. If SaveBeforeClose is false, then the software should be exited, no matter what for the testing to work.
2. If SaveBeforeClose is true, the software should not close straight away without giving the user a chance to save the work if the command was not able to save it for you.

How 2. is achieved is to me at least of secondary importance. Etabs and SAP both had a boolean input to the exit method on the API that I made use of. Robot only had something half-similar, so opted for another solution.

If you disagree with this, I can try to find an aligning solution between the toolkits :)

2021-08-26 12:37 UTC, alelom submitted a review, later dismissed
LGTM, only looked at the code.

2021-08-31 14:43 UTC, IsakNaslundBh commented
@BHoMBot check required

2021-09-01 07:42 UTC, IsakNaslundBh commented
@BHoMBot check required

2021-09-01 15:06 UTC, alelom approved these changes
LGTM. Tested, works as expected.

2021-09-07 15:36 UTC, IsakNaslundBh commented
@BHoMBot check dataset-compliance

2021-09-08 07:16 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2021-09-08 07:17 UTC, merged