Update FramingElementDesignProperties.cs
BHoM/Robot_Toolkit pull request #487
Opened 2022-02-23 10:42 UTC by Martian42

Try catch is added around the if statement that causes the pulling method to crash in Grasshopper when pulling Robot model.

It is encouraged to review and update FramingElementDesignProperties in the future.

 ### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #

 

 ### Test files

 ### Changelog

 ### Additional comments

2022-02-23 11:49 UTC, IsakNaslundBh requested changes
Would put the try catch around all the contents of this for loop, not just this part, to make sure we do not end up with a similar situation for other framing properties. This is, from line 45 all the way down to line 155.

2022-02-23 16:33 UTC, Martian42 commented
> Or, actually, at least covering all that are trying to extract the properties. This is from current position down to line 148

@IsakNaslundBh try and catch has been updated as suggested.

2022-02-24 11:31 UTC, IsakNaslundBh approved these changes
LGTM as an initial fix to make sure things does not crash.

For https://github.com/BHoM/Robot_Toolkit/issues/486 to be resolved properly in upcoming PRs.

2022-02-24 11:31 UTC, IsakNaslundBh commented
@BHoMBot check compliance
@BHoMBot check required

2022-02-24 11:47 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2022-02-24 12:45 UTC, merged